### ISSUE TITLE
blank screen of death when enabling Authentication API plugin 0.1.1

### ISSUE THREAD

**Issue by neccospb** [alberto234/wurrd-auth-api-plugin#2]
I've got a blank screen of death when enabling Authentication API plugin 0.1.1 from Mibew 2.0.1 admin panel. (Apache 2.2, php 5.5)

In /configs/config.yml i added:
plugins:
    "Wurrd:AuthAPI": # Plugin's configurations are described below
        client_id: TEST_CLIENT_ID

what am I doing wrong?
and what author mean here?

The plugin can be configured with values in "<Mibew root>/configs/config.yml" file.
config.client_id
Type: String

**Comment by alberto234** [comment]
Do you by any chance have any errors in your php error log file?

Also note that in config.yml the number of spaces at the start of the line matter, as the indentation is used to determine the configuration hierarchy. 

See http://www.yaml.org/start.html for more on YAML format

**Comment by neccospb** [comment]
You were right, the mistake was because of incorrect number of spaces. Now i recommend to use notepad++ to edit config.yml instead of other text editors.

**Comment by alberto234** [comment]
Nice. Let me know if you have other issues.

**Comment by waldierrafael** [comment]
Traductor

ayuda por favor, tengo este error: Plugin "Wurrd:AuthAPI" cannot be enabled.
/configs/config.yml

# Plugins
plugins:
  "Wurrd:AuthAPI":
    client_id: TEST_CLIENT_ID
  "Wurrd:ClientInterface":
    use_http_post: false

Hay algun error?

235/5000
help please, I have this error: Plugin "Wurrd: AuthAPI" can not be enabled.
/configs/config.yml

# Plugins
plugins:
   "Wurrd: AuthAPI":
     client_id: TEST_CLIENT_ID
   "Wurrd: ClientInterface":
     use_http_post: false

There is any error?

**Comment by waldierrafael** [comment]
help please, I have this error: Plugin "Wurrd: AuthAPI" can not be enabled.
/configs/config.yml

plugins:
   "Wurrd: AuthAPI":
     client_id: TEST_CLIENT_ID
   "Wurrd: ClientInterface":
     use_http_post: false

There is any error?

**Comment by kirillsavine** [comment]
I have same issue Plugin "Wurrd:AuthAPI" cannot be enabled
Please assist

I was getting this error before and after editing the config file
